@startuml

skinparam defaultFontName Arial
skinparam defaultTextAlignment center

Actor user

package "<b>Demo system</b>\n[Software system]" <<Software system>> {
    component "<b>Demo application</b>\n<u>[Container: Spring]</u>\nSimple application\nthat serves user information" <<Container>> as app
    database "<b>Database</b>\n<u>[Container: H2]</u>\n\nUsed for store user information" <<Container>> as db
}

component "Details system \n[Software system]" <<Software system>> as details

package "<b>Testing system</b>\n[Software system]" <<Software system>> {
    component "<b>Grafana</b>\n\nUsed for monitoring" <<Container>> as grafana
    component "<b>K6</b>\n\nLoad testing tool" <<Container>> as k6
    database "<b>Metrics database</b>\n<u>[Container: influxDB]</u>\n\nUsed for store metrics" as influxdb
    component "<b>Prometheus</b>\n\nUsed for metrics" <<Container>> as prometheus
}


user -.-> k6 : run k6 script
user -.-> grafana : check results\nin GUI application

grafana -.-> influxdb : get metrics
grafana -.-> prometheus : fetch metrics

k6 -.left-> app : call application REST endpoint
k6 -.-> influxdb : send test metrics

prometheus -.left-> app : pull metrics
app -.-> db : fetch data\n[jdbc]
app -.-> details : gets detailed info about user\n[REST]





@enduml